config/routes.rb
GetTickets::Application.routes.draw do
  get '/' => "pages#home"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/login', to: 'pages#login', as: 'login'


  # devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :invites
  resources :notifications, only: [:update]
  resources :users do
    resources :invites, shallow: true
  end

  resource :plan, only: [] do
    get :demo_closed
    get :demo_open
  end

  resources :plans do
    resources :invites, shallow: true
    resources :tickets, shallow: true
  end




  resources :media, only: [:create, :destroy]

  get '/about' => "pages#aboutus"
  get '/terms' => "pages#terms"
  get '/privacy' => "pages#privacy"
  get '/support' => "pages#support"
  get '/landing' => "pages#landing", as: :landing

end

app/models/plan.rb
# when    datetime 
# what          string   
# description   text     
# where         string   
# deadline       datetime 
# price         integer  
# user_id       integer  
# lat           decimal  
# lng           decimal  
# status        string         default: "open"
# image         string   
# booked        boolean        default: false

class Plan < ActiveRecord::Base
	belongs_to :host, :class_name => "User", foreign_key: "user_id"
	has_many :invites, dependent: :destroy
  has_many :guests, through: :invites, source: :guest
  has_many :media

  serialize :latlng, Hash

  attr_accessor :timezone

  DATEFORMAT = "%d/%m/%Y %H:%M"

  def self.date_display_format
    DATEFORMAT
  end

  def self.datetimezone_format
    DATEFORMAT + " %Z"
  end

  def host?(user)
    user == host
  end

  def no_invites?
    guests.count < 2
  end

  def booked?
    booked
  end

  def not_booked?
    !booked?
  end

  def confirmed?
    closed? && booked?
  end

  def unconfirmed?
    open? || !booked?
  end

  def open?
    status == 'open'
  end

  def closed?
    status == 'closed'
  end

  def booking_reminder?
    closed? && not_booked?
  end

  def unregistered?
    host.guest_user?
  end

  def check_status
    if deadline <= DateTime.now
      update(status: "closed")
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :check_plan_status, only: [:show]
  before_filter :set_view_path, only: [:show]
  before_filter :set_demo_end_date, only: [:demo_open]
  helper_method :current_plan

  def index
    @plans = ::Query::User::Plans.all(current_user)
  end

  def show
    @plan = ::Presenter::Plan.new(current_plan, current_user, view_context)
  end

  def edit
    @plan = ::PlanForm.new(current_plan)
  end

  def create
    ::Hopscotch::Runner.call_each(
      -> { @plan = ::Service::Plan::Create.call(current_user, plan, params[:plan]) },
      -> { ::Service::Plan::Invite::Create.call(invite, plan.model, current_user, 'going')},
      success: -> { redirect_to plan_path(@plan) },
      failure: -> (msg) { render action: 'new' }
    )
  end


  def update
    ::Hopscotch::Runner.call_each(
      -> { ::Service::Plan::UpdateRecord.call(current_plan, params[:plan]) },
      -> { ::Service::Plan::Guests::SendNotifications.call(current_plan, notice: 'notify_guests')},
      success: -> { redirect_to plan_path(current_plan) },
      failure: -> (msg) { render action: 'edit' }
    )
  end


  def destroy
    # there is no links to destroy atm
    current_plan.destroy
    redirect_to plans_url
  end

  def demo_closed
    @plan = ::Presenter::Plan.new(demo_plan_closed, demo_user, view_context)
    set_demo_views
  end

  def demo_open
    @plan = ::Presenter::Plan.new(demo_plan_open, demo_user, view_context)
    set_demo_views
  end

  private

  def plan
    @plan ||= ::PlanForm.new(Plan.new)
  end
  helper_method :plan

  def invite
    @invite ||= ::InviteForm.new(Invite.new)
  end
  helper_method :invite

  def demo_plan_closed
    ::Query::Plan::Demo.closed
  end

  def demo_plan_open
    ::Query::Plan::Demo.open
  end

  def demo_user
    User.where(demo: true).first
  end

  def user_type
    (current_user == current_plan.host) ? "planner" : "guest"
  end

  def set_view_path
    prepend_view_path("#{Rails.root}/app/views/#{user_type}")
  end

  def set_demo_views
    prepend_view_path("#{Rails.root}/app/views/planner")
    render template: 'planner/plans/show'
  end

  def set_demo_end_date
    demo_plan_open.update(deadline: Time.now + 3.days)
  end

  def current_plan
    @current_plan ||= Plan.find(params[:id])
  end

  def check_plan_status
    current_plan.check_status
  end

end

app/views/planner/plans/_add_media.html.slim
.row.np
  .col-xs-12.content-module.add-media
    .row
      .col-xs-12
        p Build the hype with some content:
    .row.media-icons
      .col-xs-4 data-media-type="image"
        i class="fa fa-image"
        p add an Image
      .col-xs-4 data-media-type="youtube"
        i class="fa fa-youtube-play"
        p add a Video
      .col-xs-4 data-media-type="spotify"
        i class="fa fa-spotify"
        p add Music
    .row
      .col-xs-12
        = render "forms"

app/views/planner/plans/_booking_reminder.html.slim
.row.np
  .col-xs-12.content-module.alert.alert-info.alert-dismissable.fade.in
    button.close aria-label="Close" data-dismiss="alert" type="button" 
      span aria-hidden="true"  &times;
    .row.host-confirm-ticket
      .col-xs-8
        p.inline Have you bought the tickets?
      .col-xs-4.ticket-form.inline
        = form_for @plan.plan, remote: true do |f|
          = f.check_box :booked, checked: true, hidden: true
          .btn.btn-success.ticket-confirm.inline Yes
          .btn.btn-danger.inline.dismiss-alert No
          = f.submit

app/views/planner/plans/_demo_header.html.slim
section.demo-header
  h3 Demo Plan
  .demo-switch-container
    p Viewing as:
    .btn-group aria-label="..." role="group"
      button.btn.open type="button" class="#{@plan.open_btn_class}"
        = link_to 'Open', demo_open_plan_path
      button.btn.closed type="button" class="#{@plan.closed_btn_class}"
        = link_to 'Closed', demo_closed_plan_path

app/views/planner/plans/_forms.html.slim
- @plan.forms.each do |k, media| 
  = render partial: "#{k.to_s}_form", locals: { media: media}

app/views/planner/plans/_image_form.html.slim
.hidden.image-form.form
  = simple_form_for media, url: media_path do |f|
    = f.input :url, label: false, placeholder: 'Enter image url'
    = f.input :plan_id, as: :hidden, input_html: {value: @plan.plan.id}
    = f.input :media_type, as: :hidden, input_html: {value: "image"}
    = f.button :submit, 'Add Image', class: 'btn-green'

app/views/planner/plans/_manage_event.html.slim
.row.np
  .col-xs-12.content-module
    .row.controls
      .col-xs-4
        .detail-label
          .fb-send data-href="http://www.planndit.com#{event_path(@plan.plan)}"
          p Invite friends
      .col-xs-4.highlight
        = link_to edit_event_path(@plan.plan)
          .detail-label
            i.fa.fa-edit
            p Edit Plan
      .col-xs-4.highlight
        .detail-label
          i.fa.fa-life-ring
          p Help

app/views/planner/plans/_manage_plan.html.slim
.row.np
  .col-xs-12.content-module
    .row.controls
      .col-xs-4
        .detail-label
          .fb-send data-href="http://www.planndit.com#{plan_path(@plan.plan)}"
          p Invite friends
      .col-xs-4.highlight
        = link_to edit_plan_path(@plan.plan)
          .detail-label
            i.fa.fa-edit
            p Edit Plan
      .col-xs-4.highlight
        .detail-label
          i.fa.fa-life-ring
          p Help

app/views/planner/plans/_owner_sign_in.html.slim
.row.np
  .col-xs-12.content-module.alert.alert-danger
    .row
      .col-xs-8
        p You are currently anonymous. If you would like to save the plan and invite friends you will need to log in.
      .col-xs-4
        .login-btn
          = link_to "Log in with Facebook", "/auth/facebook?origin=" +  @current_path, id: "sign_in", class: "btn btn-primary" 

app/views/planner/plans/_spotify_form.html.slim
.hidden.spotify-form.form
  = simple_form_for media, url: media_path do |f|
    = f.input :url, label: false, placeholder: 'Enter Spotify link'
    = f.input :plan_id, as: :hidden, input_html: {value: @plan.plan.id}
    = f.input :media_type, as: :hidden, input_html: {value: "spotify"}
    = f.button :submit, 'Add Song', class: 'btn-green'

app/views/planner/plans/_youtube_form.html.slim
.hidden.youtube-form.form
  = simple_form_for media, url: media_path do |f|
    = f.input :url, label: false, placeholder: 'Enter YouTube link'
    = f.input :plan_id, as: :hidden, input_html: {value: @plan.plan.id}
    = f.input :media_type, as: :hidden, input_html: {value: "youtube"}
    = f.button :submit, 'Add Video', class: 'btn-green'

app/views/planner/plans/show.html+touch.slim
- content_for :page_title do
  title
    | #{@plan.what.titleize} are playing!
- content_for :meta_description do
  meta content="I'm going to buy tickets for #{@plan.what.titleize}. Let me know if you want to go." name="description"

.notifications.tile
  .row
    .col-xs-12
      = render "notifications"
      = render "owner_sign_in"     if @plan.unregistered?
      = render "booking_reminder"  if @plan.booking_reminder?
.main
  .row
    .col-xs-12
      = render "plan_title"
      = render "manage_plan"

      = render "cost"
      = render "plan_description" if @plan.description.present?
      = render "when"
      = render "where"
      = render "add_media"
      = render "youtube"           if @plan.video
      = render "image_tile"        if @plan.image
      = render "spotify"           if @plan.music
      = render "countdown"         if @plan.open?
      = render "guest_status"
      = render "guestlist"

app/views/planner/plans/show.html.slim
- content_for :page_title do
  title
    | #{@plan.what.titleize} are playing!
- content_for :meta_description do
  meta content="I'm going to buy tickets for #{@plan.what.titleize}. Let me know if you want to go." name="description"

- if current_path.include?('demo')
  = render 'demo_header'

.main-container
  .notifications.tile
    .row
      .col-xs-12
        = render "notifications"
        = render "owner_sign_in"     if @plan.unregistered?
        = render "booking_reminder"  if @plan.booking_reminder?
  .main
    .row
      .col-xs-12
        = render "plan_title"
    .row
      .col-sm-6.pleft
        = render "cost"
        = render "when"
        = render "where"
        = render "spotify"           if @plan.music
        = render "image_tile"        if @plan.image
        = render "youtube"           if @plan.video
      .col-sm-6.pright
        - if @plan.open?
          = render "manage_plan"
          = render "add_media"
          = render "countdown"
        = render "guest_status"
        = render "youtube"           if @plan.video

        = render "plan_description"    if @plan.description.present?
        = render "guestlist"