config/routes.rb
GetTickets::Application.routes.draw do
  get '/' => "pages#home"
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/login', to: 'pages#login', as: 'login'


  # devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :invites
  resources :notifications, only: [:update]
  resources :users do
    resources :invites, shallow: true
  end

  resource :plan, only: [] do
    get :demo_closed
    get :demo_open
  end

  resources :plans do
    resources :invites, shallow: true
    resources :tickets, shallow: true
  end




  resources :media, only: [:create, :destroy]

  get '/about' => "pages#aboutus"
  get '/terms' => "pages#terms"
  get '/privacy' => "pages#privacy"
  get '/support' => "pages#support"
  get '/landing' => "pages#landing", as: :landing

end

app/views/layouts/_facebook_sdk.html.erb
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=866294993397299";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

app/views/layouts/_googleanalytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-47891202-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation" 
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/" 
        span
          = image_tag 'planndit_icon_flipped.png', class: "small-p"
          | planndit
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li= link_to "My Events", events_path
        li= link_to "Create an Event", new_event_path
        - if authenticated_user
          li= link_to "Sign out", signout_path, id: "sign_out", :class => 'navbar-link'
        - else
          li= link_to "Log in with Facebook", ("/auth/facebook?origin=" +  @current_path) , id: "sign_in"

app/views/layouts/_nav.html.slim
nav.navbar.navbar-default role="navigation" 
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#navbar-toggle" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/" 
        span
          = image_tag 'planndit_icon_flipped.png', class: "small-p"
          | planndit

    #navbar-toggle.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li= link_to "My Plans", plans_path
        li= link_to "Create a Plan", new_plan_path
        - if authenticated_user
          li= link_to "Sign out", signout_path, id: "sign_out", :class => 'navbar-link'
        - else
          li= link_to "Log in", ("/auth/facebook?origin=" +  @current_path) , id: "sign_in"

app/views/layouts/_nav_no_brand.html.slim
nav.navbar.navbar-default role="navigation" 
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#navbar-toggle" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar

    #navbar-toggle.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li= link_to "My Plans", plans_path if current_user.plans.present?
        - if authenticated_user
          li= link_to "Sign out", signout_path, id: "sign_out", :class => 'navbar-link'
        - else
          li= link_to "Log in", ("/auth/facebook?origin=" +  @current_path) , id: "sign_in"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = yield :meta_description
    = yield :page_title
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag
    = render "layouts/googleanalytics"
  body
    = render "layouts/nav"
    .main-container
      = yield
    = render "layouts/facebook_sdk"
    footer
      ul.footer
        li= link_to 'About Us', '/about'
        li= link_to 'Contact Us', '/contact'

app/views/layouts/events.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = yield :meta_description
    = yield :page_title
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js", "data-turbolinks-track" => true
    = csrf_meta_tag

    = render "layouts/googleanalytics"
  body
    .page-wrap
      = render "layouts/nav"
      = yield
    footer
      ul.footer
        li= link_to 'About Us', '/about'
        li= link_to 'Contact Us', '/contact'
    = render "layouts/facebook_sdk"

app/views/layouts/green.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = yield :meta_description
    = yield :page_title
    = stylesheet_link_tag "green", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js", "data-turbolinks-track" => true
    = csrf_meta_tag
    link href="#{image_path('/apple-touch-icon-57x57.png')}" rel="apple-touch-icon" sizes="57x57" /
    link href="#{image_path('/apple-touch-icon-60x60.png')}" rel="apple-touch-icon" sizes="60x60" /
    link href="#{image_path('/apple-touch-icon-72x72.png')}" rel="apple-touch-icon" sizes="72x72" /
    link href="#{image_path('/apple-touch-icon-76x76.png')}" rel="apple-touch-icon" sizes="76x76" /
    link href="#{image_path('/favicon-32x32.png')}" rel="icon" sizes="32x32" type="image/png" /
    link href="#{image_path('/favicon-96x96.png')}" rel="icon" sizes="96x96" type="image/png" /
    link href="#{image_path('/favicon-16x16.png')}" rel="icon" sizes="16x16" type="image/png" /
    link href="#{image_path('/manifest.json')}" rel="manifest" /
    link color="#00b62f" href="/safari-pinned-tab.svg" rel="mask-icon" /
    meta content="#da532c" name="msapplication-TileColor" /
    meta content="#00b62f" name="theme-color" /
    = render "layouts/googleanalytics"
  body.green
    = yield :nav_bar
    = yield

app/views/layouts/plans.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = yield :meta_description
    = yield :page_title
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js", "data-turbolinks-track" => true
    = csrf_meta_tag

    = render "layouts/googleanalytics"
  body
    .page-wrap
      = render "layouts/nav"
      = yield
    footer
      ul.footer
        li= link_to 'About Us', '/about'
        li= link_to 'Contact Us', '/contact'
    = render "layouts/facebook_sdk"